### ISSUE TITLE
Are input QVs meaningful? 

### ISSUE THREAD

**Issue by armintoepfer** [yangao07/abPOA#3]
Hi!

Quick question: From SPOA I've learned that leveraging per-base quality values to weight nodes in the graph increases the accuracy of the generated consensus, especially using PacBio HiFi as input. Have you experimented with such feature?

Thanks,
Armin

**Comment by yangao07** [comment]
Hi Armin,

Right now abPOA does not use any quality information in the FASTQ file input.
We do plan to implement something like SPOA does to make use of the quality score during the consensus calling step.
Will keep you posted if we make any updates on that.

Yan

**Comment by brendanf** [comment]
As far as I can tell, in SPOA this is simply implemented by weighting each incoming base by its quality score; i.e., instead of incrementing the count for each node by 1 each time a new sequence aligns to it, increment it by the quality value for the base which aligns to the node.  The quality scores are integers, so nothing else needs to change about the data structure or consensus-calling algorithms, that I'm aware of.  Would that be difficult to implement in abPOA?

**Comment by yangao07** [comment]
> As far as I can tell, in SPOA this is simply implemented by weighting each incoming base by its quality score; i.e., instead of incrementing the count for each node by 1 each time a new sequence aligns to it, increment it by the quality value for the base which aligns to the node. The quality scores are integers, so nothing else needs to change about the data structure or consensus-calling algorithms, that I'm aware of. Would that be difficult to implement in abPOA?

You are right, it is straightforward. Let me work on this.

**Comment by yangao07** [comment]
Try the latest abPOA which could take base quality scores as weights.

**Comment by brendanf** [comment]
Thanks, this is great!
